import { Lead, Tenant, Vendedor } from './types';

// ============================================================
// TENANTS — Copiloto IA
// ============================================================

export const TENANTS: Record<string, Tenant> = {
    'world-games': {
        id: 'world-games',
        name: 'World Games',
        primaryColor: '#FDB813',    // Amarelo vibrante da marca
        secondaryColor: '#1e3a5f',  // Azul escuro profundo
        accentColor: '#22c55e',     // Verde festivo (accent)
        logoText: 'WG',
        slug: 'world-games',
        nicho: 'eventos_infantis',
    },
    'default': {
        id: 'default',
        name: 'Kiko Bim Imóveis',
        primaryColor: '#d4af37',
        secondaryColor: '#1e293b',
        logoText: 'KB',
        slug: 'kiko-bim',
    },
    'investt': {
        id: 'investt',
        name: 'Investt Imóveis',
        primaryColor: '#3b82f6',
        secondaryColor: '#eff6ff',
        logoText: 'IV',
        slug: 'investt',
    },
};

// ── Tenant padrão ─────────────────────────────────────────────
export const ACTIVE_TENANT = TENANTS['world-games'];

// ============================================================
// VENDEDORES — Equipe de Eventos
// ============================================================

export const MOCK_VENDEDORES: Vendedor[] = [
    {
        id: 'v1',
        nome: 'Camila Rocha',
        email: 'camila@worldgames.com.br',
        avatar_iniciais: 'CR',
        cor_avatar: 'bg-pink-500',
        ativo: true,
    },
    {
        id: 'v2',
        nome: 'Rafael Souza',
        email: 'rafael@worldgames.com.br',
        avatar_iniciais: 'RS',
        cor_avatar: 'bg-blue-500',
        ativo: true,
    },
    {
        id: 'v3',
        nome: 'Jéssica Alves',
        email: 'jessica@worldgames.com.br',
        avatar_iniciais: 'JA',
        cor_avatar: 'bg-violet-500',
        ativo: true,
    },
    {
        id: 'v4',
        nome: 'Bruno Mendes',
        email: 'bruno@worldgames.com.br',
        avatar_iniciais: 'BM',
        cor_avatar: 'bg-emerald-500',
        ativo: false,
    },
];

// ============================================================
// MOCK LEADS — Clientes buscando Festas & Eventos Infantis
// ============================================================

export const MOCK_LEADS: Lead[] = [
    {
        id: 'l1',
        created_at: '2026-02-10 09:14:22',
        telefone: '11984523610',
        nome: 'Mariana Ferreira',
        nome_crianca: 'Sofia',
        tipo_servico: 'festa',
        data_evento: '2026-03-15',
        qtd_criancas: 30,
        tema_festa: 'Princesa Sofia',
        local_preferido: 'no_espaco',
        orcamento_estimado: 4500,
        temperatura: 'muito_quente',
        resumo: 'Cliente quer pacote completo para festa da Sofia (5 anos). Tema Princesa Sofia. Quer visitar o espaço esta semana.',
        fup_pendente: true,
        etapa_funil: 'visita_espaco',
        ultimo_contato: '2026-02-25 14:30:00',
        vendedor_id: 'v1',
        tags: ['Orçamento Enviado'],
    },
    {
        id: 'l2',
        created_at: '2026-02-11 10:05:44',
        telefone: '13956120894',
        nome: 'Patricia Lima',
        nome_crianca: 'Pedro',
        tipo_servico: 'festa',
        data_evento: '2026-04-05',
        qtd_criancas: 50,
        tema_festa: 'Super-Heróis',
        local_preferido: 'no_espaco',
        orcamento_estimado: 7200,
        temperatura: 'muito_quente',
        resumo: 'Contrato praticamente fechado. Aguardando comprovante do sinal para confirmar data.',
        fup_pendente: false,
        etapa_funil: 'fechamento',
        ultimo_contato: '2026-02-26 09:00:00',
        vendedor_id: 'v2',
        tags: ['Aguardando Sinal'],
    },
    {
        id: 'l3',
        created_at: '2026-02-12 11:22:10',
        telefone: '14998204511',
        nome: 'Roberto Carvalho',
        nome_crianca: 'Luísa',
        tipo_servico: 'espaco_kids',
        data_evento: '2026-03-22',
        qtd_criancas: 20,
        tema_festa: 'Frozen',
        local_preferido: 'no_espaco',
        orcamento_estimado: 3100,
        temperatura: 'quente',
        resumo: 'Interessado no pacote Espaço Kids. Perguntou sobre disponibilidade no sábado.',
        fup_pendente: true,
        etapa_funil: 'orcamento',
        ultimo_contato: '2026-02-24 16:45:00',
        vendedor_id: 'v3',
        tags: ['Espaço Kids'],
    },
    {
        id: 'l4',
        created_at: '2026-02-13 14:00:00',
        telefone: '17991382544',
        nome: 'Fernanda Oliveira',
        nome_crianca: 'Miguel',
        tipo_servico: 'recreacao',
        data_evento: '2026-03-29',
        qtd_criancas: 80,
        tema_festa: 'Corinthians',
        local_preferido: 'em_casa',
        orcamento_estimado: 2800,
        temperatura: 'quente',
        resumo: 'Evento corporativo com kids zone. Precisa de recreadores para evento em condomínio.',
        fup_pendente: false,
        etapa_funil: 'contato',
        ultimo_contato: '2026-02-25 10:10:00',
        vendedor_id: 'v1',
        tags: ['Recreação'],
    },
    {
        id: 'l5',
        created_at: '2026-02-14 08:55:00',
        telefone: '17996881023',
        nome: 'Amanda Souza',
        nome_crianca: 'Valentina',
        tipo_servico: 'festa',
        data_evento: '2026-05-10',
        qtd_criancas: 40,
        tema_festa: 'Bita e os Animais',
        local_preferido: 'no_espaco',
        orcamento_estimado: 5500,
        temperatura: 'morno',
        resumo: 'Orçamento enviado por e-mail. Cliente ainda comparando com outros espaços.',
        fup_pendente: true,
        etapa_funil: 'orcamento',
        ultimo_contato: '2026-02-23 15:20:00',
        vendedor_id: 'v2',
        tags: ['Orçamento Enviado', 'FUP Atrasado'],
    },
    {
        id: 'l6',
        created_at: '2026-02-15 13:30:00',
        telefone: '17997123456',
        nome: 'Carlos Eduardo',
        nome_crianca: 'Gael',
        tipo_servico: 'festa',
        data_evento: '2026-03-08',
        qtd_criancas: 25,
        tema_festa: 'Dinossauros',
        local_preferido: 'no_espaco',
        orcamento_estimado: 3800,
        temperatura: 'muito_quente',
        resumo: 'Sinal pago! Festa confirmada para 08/03. Verificar decoração e cardápio.',
        fup_pendente: false,
        etapa_funil: 'confirmado',
        ultimo_contato: '2026-02-26 11:00:00',
        vendedor_id: 'v3',
        tags: ['Festa Confirmada'],
    },
    {
        id: 'l7',
        created_at: '2026-02-16 09:00:00',
        telefone: '19992345678',
        nome: 'Luciana Mendes',
        nome_crianca: 'Clara',
        tipo_servico: 'espaco_kids',
        data_evento: undefined,
        qtd_criancas: 15,
        tema_festa: undefined,
        local_preferido: 'no_espaco',
        orcamento_estimado: undefined,
        temperatura: 'frio',
        resumo: 'Perguntou sobre valores gerais do Espaço Kids. Ainda sem data definida.',
        fup_pendente: false,
        etapa_funil: 'novo',
        ultimo_contato: '2026-02-20 09:00:00',
        vendedor_id: undefined,
        tags: ['Espaço Kids', 'Lead Frio'],
    },
    {
        id: 'l8',
        created_at: '2026-02-17 15:10:00',
        telefone: '18991234509',
        nome: 'Juliana Pires',
        nome_crianca: 'Arthur',
        tipo_servico: 'festa',
        data_evento: '2026-04-20',
        qtd_criancas: 60,
        tema_festa: 'Minecraft',
        local_preferido: 'no_espaco',
        orcamento_estimado: 8000,
        temperatura: 'quente',
        resumo: 'Lead VIP. Quer pacote premium com buffet completo, DJ e decoração exclusiva.',
        fup_pendente: true,
        etapa_funil: 'visita_espaco',
        ultimo_contato: '2026-02-25 17:00:00',
        vendedor_id: 'v1',
        tags: ['VIP', 'Orçamento Enviado'],
    },
    {
        id: 'l9',
        created_at: '2026-02-18 10:22:00',
        telefone: '17988541209',
        nome: 'Tatiane Gomes',
        nome_crianca: 'Bento',
        tipo_servico: 'recreacao',
        data_evento: '2026-03-14',
        qtd_criancas: 35,
        tema_festa: 'Festa Junina',
        local_preferido: 'em_casa',
        orcamento_estimado: 1800,
        temperatura: 'morno',
        resumo: 'Precisa de recreadores para festa junina no salão do condomínio.',
        fup_pendente: false,
        etapa_funil: 'contato',
        ultimo_contato: '2026-02-24 08:30:00',
        vendedor_id: 'v2',
        tags: ['Recreação'],
    },
    {
        id: 'l10',
        created_at: '2026-02-19 11:00:00',
        telefone: '17996374894',
        nome: 'Beatriz Castro',
        nome_crianca: 'Helena',
        tipo_servico: 'festa',
        data_evento: '2026-06-01',
        qtd_criancas: 45,
        tema_festa: 'Barbie',
        local_preferido: 'no_espaco',
        orcamento_estimado: 6500,
        temperatura: 'morno',
        resumo: 'Mama de aniversário perguntou sobre decoração rosa. Aguarda proposta.',
        fup_pendente: true,
        etapa_funil: 'novo',
        ultimo_contato: '2026-02-22 16:50:00',
        vendedor_id: undefined,
        tags: [],
    },
    {
        id: 'l11',
        created_at: '2026-02-20 08:45:00',
        telefone: '11977081234',
        nome: 'Diego Ramos',
        nome_crianca: 'Lorenzo',
        tipo_servico: 'espaco_kids',
        data_evento: '2026-03-30',
        qtd_criancas: 22,
        tema_festa: 'Hot Wheels',
        local_preferido: 'no_espaco',
        orcamento_estimado: 3500,
        temperatura: 'quente',
        resumo: 'Visitou o espaço ontem, gostou muito. Aguardando confirmação do pacote médio.',
        fup_pendente: false,
        etapa_funil: 'fechamento',
        ultimo_contato: '2026-02-26 14:00:00',
        vendedor_id: 'v3',
        tags: ['Espaço Kids', 'Aguardando Sinal'],
    },
    {
        id: 'l12',
        created_at: '2026-02-21 09:15:00',
        telefone: '13988765432',
        nome: 'Sandra Nogueira',
        nome_crianca: 'Isabela',
        tipo_servico: 'festa',
        data_evento: '2026-04-12',
        qtd_criancas: 55,
        tema_festa: 'Pequena Sereia',
        local_preferido: 'no_espaco',
        orcamento_estimado: 7000,
        temperatura: 'muito_quente',
        resumo: 'Sinal confirmado! Contrato assinado digitalmente. Festa da Isabela garantida.',
        fup_pendente: false,
        etapa_funil: 'confirmado',
        ultimo_contato: '2026-02-26 10:30:00',
        vendedor_id: 'v2',
        tags: ['Festa Confirmada', 'VIP'],
    },
];